# Generated by Django 4.1.7 on 2023-03-30 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_articulo_autor_alter_articulo_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='Autor',
            new_name='autor',
        ),
    ]
