# Generated by Django 4.1.7 on 2023-04-03 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='cuerpo',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='fecha',
            new_name='date',
        ),
    ]
