# Generated by Django 4.1.7 on 2023-04-03 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_rename_autor_comentario_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='pertenencia',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.articulo'),
        ),
    ]
