# Generated by Django 4.1.7 on 2023-04-03 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0006_comentario_pertenencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='pertenencia',
        ),
        migrations.AddField(
            model_name='comentario',
            name='remitente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remitente', to=settings.AUTH_USER_MODEL),
        ),
    ]
