# Generated by Django 4.1.7 on 2023-04-04 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_remove_comentario_pertenencia_comentario_remitente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='remitente',
        ),
        migrations.AddField(
            model_name='comentario',
            name='pertenencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentariosArts', to='blogs.articulo'),
        ),
    ]
