# Generated by Django 4.1.7 on 2023-04-04 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_remove_comentario_remitente_comentario_pertenencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='pertenencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='blogs.articulo'),
        ),
    ]
