# Generated by Django 4.1.7 on 2023-04-04 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_alter_comentario_pertenencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='pertenencia',
            new_name='articulo',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='body',
            new_name='comentar',
        ),
    ]
