# Generated by Django 4.1.7 on 2023-04-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_respcom'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='titulo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
