# Generated by Django 4.1.7 on 2023-04-05 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_comentario_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respcom',
            name='respuesta',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.comentario'),
        ),
    ]
