# Generated by Django 4.1.7 on 2023-04-05 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_alter_respcom_respuesta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RespCom',
        ),
    ]
